[project]
name = "helath-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django-ninja>=1.3.0",
    "uvicorn>=0.34.0",
]
