# Generated by Django 5.1.4 on 2025-01-06 13:31

import src.core.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="carb",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="meal",
            name="fat",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="meal",
            name="kcal",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="meal",
            name="protein",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="plan",
            name="carb",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="fat",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="plan",
            name="kcal",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="plan",
            name="protein",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="carb",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="fat",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="kcal",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
        migrations.AlterField(
            model_name="planrecord",
            name="protein",
            field=src.core.db.fields.PrecisedFloatField(),
        ),
    ]
