name: Build and Push

on:
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  DOCKER_REPO: ${{ vars.DOCKER_REPO }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }} .

      - name: Push image
        run: docker push ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
