name: Palumi
on:
  push:
jobs:
  django-tests:
     runs-on: ubuntu-latest
     services:
       postgres:
         image: postgres:latest
         env:
           POSTGRES_PASSWORD: postgres
           POSTGRES_USER: postgres
           POSTGRES_DB: postgres
         ports:
           - 5432:5432
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

     steps:
       - uses: actions/checkout@v4
       - name: Build image
         run: make build-ci-app
       - name: Run tests
         run: make run-ci-test \
              POSTGRES_PASSWORD=postgres \
              POSTGRES_USER=postgres \
              POSTGRES_DB=postgres \
              POSTGRES_HOST=localhost \
              POSTGRES_PORT=5432
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
